# Generated by Django 4.1.3 on 2022-12-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('length', models.CharField(max_length=30)),
                ('actors', models.ManyToManyField(blank=True, to='actors.actors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.CharField(max_length=40)),
                ('actors', models.ManyToManyField(blank=True, to='actors.actors')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
